#!/bin/sh
step=5

case $1 in 
	# increase brightness
	-i) 
        light -s sysfs/leds/smc::kbd_backlight -A `echo $step` 
		;;
	# decrease brightness
	-d)
        light -s sysfs/leds/smc::kbd_backlight -U `echo $step`
		;;
esac
#current=$(light -s sysfs/leds/smc::kbd_backlight -G)
#notify-send -a Keyboard -i ~/.config/icons/backlight.svg "Backlight brightness `printf %.0f $(echo "$current" | bc -l)`%" -h "int:value:$current" -h string:x-dunst-stack-tag:backlight
