#!/bin/bash
# constants 

declare -i LowBatteryMark=16

STATUS=$(cat /sys/class/power_supply/BAT0/status)
BATT=$(cat /sys/class/power_supply/BAT0/capacity)

if [[ $BATT -lt $LowBatteryMark && "$STATUS" != "Charging" ]]; then 
    $(notify-send -i ~/.config/icons/battery.png "Battery Low" "Please plug in" -a Danger -u critical)
    #aplay -q ~/.config/audio/low_battery.wav
fi
