#!/bin/sh

step=5
case $1 in 
	# increase brightness
	-i) 
        	light -A `echo $step`
		;;
	# decrease brightness
	-d)
        	light -U `echo $step`
		;;
esac
#notify-send -a Brightness -i ~/.config/icons/monitor.png "Monitor brightness `printf %.0f $(light | bc -l)`%" -h "int:value:$(light)" -h string:x-dunst-stack-tag:Monitor
pkill -RTMIN+10 dwmblocks
