#! /bin/sh

case $1 in
	on)
		xrandr --setmonitor external auto HDMI1
		xrandr --output HDMI1 --mode 1920x1080 --left-of eDP1
		xrandr --output eDP1 --off
		;;
	off)
		xrandr --output eDP1 --auto
		xrandr --output HDMI1 --off
		;;
esac
