#! /bin/sh

case $1 in
	on)
		xrandr --setmonitor external auto HDMI1
		xrandr --output HDMI1 --mode 1920x1080 --left-of eDP1
		;;
	off)
		xrandr --output HDMI1 --off
		xrandr -delmonitor external
		;;
esac
