#!/bin/bash

# loading colors
. ~/.config/scripts/bar_themes/onedark

# CPU
read cpu a b c previdle rest < /proc/stat
prevtotal=$((a+b+c+previdle))
sleep 0.5
read cpu a b c idle rest < /proc/stat
total=$((a+b+c+idle))
cpu=$((100*( (total-prevtotal) - (idle-previdle) ) / (total-prevtotal) ))

#echo "^b$darkblue^ CPU ^b$grey^  $cpu% ^b$black^"

#printf "^c$black^ ^b$green^ CPU"
#printf "^c$white^ ^b$grey^ $cpu"
echo "^b$blue^ CPU $cpu"
