#!/bin/bash

# constants 

declare -r BatteryNotificationStatePath=~/.config/tmp/Notifications/LowBatterySent
declare -i LowBatteryMark=16

STATUS=$(cat /sys/class/power_supply/BAT0/status)
BATT=$(cat /sys/class/power_supply/BAT0/capacity)
#BATTTEMP=$(cat /sys/class/power_supply/BAT0/temp)
NOTIFIED=$(cat $BatteryNotificationStatePath)

if [ "$STATUS" = "Discharging" ]; then
  ICON="Batt"
	#if [ $BATT -gt 80 ]; then
	#	ICON="🔋"
	#elif [ $BATT -gt 60 ]; then
  #     		ICON=""
	#elif [ $BATT -gt 40 ]; then
  #      	ICON=""
	#elif [ $BATT -gt 20 ]; then
  #      	ICON=""
	#else
  #      	ICON="🪫"
	#fi
else
	#ICON="⚡"
	ICON="Plug"
	if [[ $BATT -gt $LowBatteryMark && "$NOTIFIED" -eq "Yes" ]]; then 
		$(echo "No" > $BatteryNotificationStatePath)
	fi
fi
if [[ $BATT -lt $LowBatteryMark && "$NOTIFIED" != "Yes" ]]; then 
    $(notify-send  "Battery Low" "Please plug in" -a Danger -u critical)
    play ~/.config/audio/notification.wav
	$(echo "Yes" > $BatteryNotificationStatePath)
fi
echo "$ICON" "$BATT%"


