#!/bin/bash
#
#vol=$(awk -F"[][]" '/Left:/ { print $2 }' <(amixer sget Master))
vol=$(pamixer --get-volume)

if [[ -n $(pamixer --get-mute | grep true) ]] 
then
	vol="${vol} MUTE"
else
	vol="${vol}"
fi
echo $vol
