#!/bin/bash 

#slstatus &
dwmblocks &
xss-lock slock &
unclutter &
setxkbmap -option ctrl:swapcaps
xset r rate 300 100 &
xrandr --output eDP-1 --off


feh --bg-tile /home/dp/.wallpapers/Arch-linux-1.png &
