#!/bin/bash

# Project: bspwm scratchpad

class="scpad-muskcube"
winclass=$(xdotool search --class $class);
if [ -z "$winclass" ];
then
     kitty --class $class musikcube
else
    if [ ! -f /tmp/$class ]; then
          touch /tmp/$class && xdo show "$winclass"
    elif [ -f /tmp/$class ]; then
          rm /tmp/$class && xdo hide "$winclass"
    fi
fi
