#!/bin/bash

# Project: bspwm scratchpad btop

class="scpad-btop"
winclass=$(xdotool search --class $class);
if [ -z "$winclass" ];
then
     kitty --class $class btop
else
    if [ ! -f /tmp/$class ]; then
          touch /tmp/$class && xdo show "$winclass"
    elif [ -f /tmp/$class ]; then
          rm /tmp/$class && xdo hide "$winclass"
    fi
fi
