#!/bin/sh

step=5
case $1 in 
	# increase Volume
	-i)
		amixer -D pulse sset Master 5%+ -q
    #notify-send -a Speaker -i ~/.config/icons/megaphone.png "Volume `printf %.0f $(pamixer --get-volume)`%" -h "int:value:$(pamixer --get-volume)" -h string:x-dunst-stack-tag:volume    
		;;
	# decrease Volume
	-d)
		amixer -D pulse sset Master 5%- -q
    #notify-send -a Speaker -i ~/.config/icons/megaphone.png "Volume `printf %.0f $(pamixer --get-volume)`%" -h "int:value:$(pamixer --get-volume)" -h string:x-dunst-stack-tag:volume    
		;;
	# Toggle Volume
	-t)
		amixer sset Master toggle -q
esac
pkill -RTMIN+11 dwmblocks
