#! /bin/sh

# autostart
pgrep -x sxhkd > /dev/null || sxhkd &
feh --bg-fill --randomize /home/deepakpatel/Images/Wallpaper &
dunst &
unclutter &
xss-lock slock &
setxkbmap -option ctrl:nocaps
xset r rate 200 50 &
bspc monitor -d 1 2 3 4 5 6 7 8 9 10 &
polybar top &
polybar bottom &

# bspwm config
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.60
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc config normal_border_color "#44475a"
bspc config presel_feedback_color "#6272a4"


bspc config active_border_color "#6272a4"
bspc config focused_border_color "#8be9fd"

# application rules
bspc rule -a Emacs state=tiled
