#! /bin/sh

# autostart
pgrep -x sxhkd > /dev/null || sxhkd &
feh --bg-fill --randomize ~/Images/OneDarkWallpapers/06.png &
dunst &
unclutter &
xss-lock slock &
setxkbmap -option ctrl:nocaps
xset r rate 200 50 &
bspc monitor eDP1 -d 1 2 3 4 &
polybar top &

# bspwm config
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.60
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc config normal_border_color "#44475a"
bspc config presel_feedback_color "#6272a4"


bspc config active_border_color "#6272a4"
bspc config focused_border_color "#8be9fd"
