#! /bin/sh

# autostart
killall -q polybar
killall picom
xrandr --output eDP-1 --off

# First EXTERNAL_MONITOR
polybar -c ~/.config/polybar/config.ini top &
polybar -c ~/.config/polybar/config.ini bottom &

# Second EXTERNAL_MONITOR 
polybar -c ~/.config/polybar/config.ini top &
polybar -c ~/.config/polybar/config.ini bottom &
sxhkd &
feh --bg-fill --randomize /home/dp/Images/Wallpaper &
xset r rate 300 100
xss-lock slock &
unclutter &
dunst &
setxkbmap -option ctrl:swapcaps &
picom &


MONITOR_0="eDP-1"
MONITOR_1="DP-1"
MONITOR_2="HDMI-1"
# on first load setup default workspaces
if [ "$1" -eq 0 ]; then
  bspc monitor "$MONITOR_1" -d 1 2 3 4 
  bspc monitor "$MONITOR_2" -d 6 7 8 9 10
  bspc wm -O "$MONITOR_2" "$MONITOR_1"
fi

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.60
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#44475a"
bspc config presel_feedback_color "#6272a4"

bspc config active_border_color "#6272a4"
bspc config focused_border_color "#8be9fd"

# scratch pads 
bspc rule -a scpad-kitty sticky=on state=floating rectangle=1700x600+100+200 
bspc rule -a scpad-btop sticky=on state=floating rectangle=1700x600+100+200 
bspc rule -a scpad-cmus sticky=on state=floating rectangle=1700x800+100+100 
bspc rule -a scpad-chat sticky=on state=floating rectangle=1700x800+100+100 

xrandr --output DP-1 --primary --mode 1920x1080 --output HDMI-1 --mode 1920x1080 --right-of DP-1
#suitup
