#! /bin/sh

# autostart
killall -q polybar
killall picom

# Laptop mode
polybar -c ~/.config/polybar/config.ini top-internal &
polybar -c ~/.config/polybar/config.ini bottom-internal &

sxhkd &
feh --bg-fill --randomize ~/Pictures/wallpaper &
xset r rate 300 100
xss-lock slock &
unclutter &
dunst &
setxkbmap -option ctrl:swapcaps &
picom --config $HOME/.config/picom/picom.conf &


MONITOR_0="eDP-1"
bspc monitor "$MONITOR_0" -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.60
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#44475a"
bspc config presel_feedback_color "#6272a4"

bspc config active_border_color "#6272a4"
bspc config focused_border_color "#8be9fd"

# scratch pads 
bspc rule -a scpad-kitty sticky=on state=floating rectangle=1700x600+100+200 
bspc rule -a scpad-btop sticky=on state=floating rectangle=1700x600+100+200 
bspc rule -a scpad-cmus sticky=on state=floating rectangle=1700x800+100+100 
bspc rule -a scpad-chat sticky=on state=floating rectangle=1700x800+100+100 

#suitup
